#!/bin/sh

set -e

lb config noauto \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--mode debian \
	--debian-installer live \
	--debian-installer-gui true \
	--archive-areas "main contrib non-free" \
	--apt-indices false \
	--security true \
	"${@}"
