#!/bin/sh

set -e

lb config noauto \
        --mode debian \
        --architectures amd64 \
        --debian-installer live \
        --debian-installer-gui true \
        --archive-areas "main contrib non-free" \
        --apt-indices false \
	--security true \
	--binary-images iso-hybrid \
        "${@}"

