#!/bin/sh

set -e

lb config noauto \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--mode debian \
	--distribution stretch \
	--debian-installer live \
	--debian-installer-gui true \
	--archive-areas "main" \
	--apt-indices true \
	--checksums md5 \
	--iso-application "Donau Lotus 1.0b" \
	--iso-publisher "The Donau Team, Spring 2020" \
	--iso-volume "Donau Lotus 1.0b" \
	"${@}"
